---
name: Puppet & YAML Validation

'on':
  push:
    paths:
      - '**.pp'
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.pp'
      - '**.yaml'
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Puppet
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget https://apt.puppet.com/puppet7-release-focal.deb
          sudo dpkg -i puppet7-release-focal.deb
          sudo apt-get update
          sudo apt-get install -y puppet-agent
          echo "/opt/puppetlabs/bin" >> $GITHUB_PATH

      - name: Validate Puppet Manifests
        run: |
          find . -type f -name "*.pp" \
            -exec /opt/puppetlabs/bin/puppet parser validate {} +

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint .
